######## Using Travis as Test Suite #######
language: generic

#specify admin access
sudo: required

#specify programs to run
sevices:
    - docker

before_install:
    #specify file path for test image build
    - docker build -t macshild/client-test -f ./client/Dockerfile.dev ./client 

    #- docker build myotherproject


#specify instructions for running test suite container
script:
    - docker run -e CI=true macshild/client-test npm run test

    #-docker run my other project

######## build prod images after successful tests##############    
after_success:
    #build express server image
    - docker build -t macshild/fib-seq-calc-express-server ./express-server

    #build client image
    - docker build -t macshild/fib-seq-calc-client-with-nginx ./client
    
    #build nginx server image
    - docker build -t macshild/fib-seq-calc-nginx-routing-server ./nginx

    #build worker image
    - docker build -t macshild/fib-seq-calc-worker ./worker

    ######### Use Travis to send prod images to docker hub ##########

    #log in to the docker cli with travis
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin #auto input pswd over stdin in docker cli

    #push image to docker hub
    - docker push macshild/fib-seq-calc-express-server
    - docker push macshild/fib-seq-calc-client-with-nginx
    - docker push macshild/fib-seq-calc-nginx-routing-server
    - docker push macshild/fib-seq-calc-worker 


 ##tell Elastic beanstalk to pull images from dockerhub by sending Dockerrun.aws.json file

######## Using Travis CI to Deploy to Elastic Beanstalk ########
deploy:
    ##fix for missing bucket_name error
    edge: true

    #specify name of hosting service
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "complicated-fibonacci-seq-calculator"
    env: "ComplicatedFibonacciSeqCalculator-env"

    #specify bucket containing zip file of  code uploaded by travis to be redeploy by AWS.
    bucket_name: "elasticbeanstalk-us-east-1-972707242260"

    #specify dir in bucket containing app files
    #use app name for a frist time scenario
    bucket_path: "complicated-fibonacci-seq-calculator"

    on:
        #specify branch in codebase that can only triger deploy to EBS
        branch: master

    #specify api keys that grants travis access to AWS
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY    




